version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ticketing-postgres
    environment:
      POSTGRES_DB: ticketingdb
      POSTGRES_USER: ticketinguser
      POSTGRES_PASSWORD: ticketingpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ticketing-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ticketing-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketing-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ticketinguser
      RABBITMQ_DEFAULT_PASS: ticketingpass123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticketing-network

  # Authentication Service
  auth-service:
    build:
      context: .
      dockerfile: src/TicketingSystem.Authentication/Dockerfile
    container_name: ticketing-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ticketingdb;Username=ticketinguser;Password=ticketingpass123;
      - JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLong12345
      - JwtSettings__Issuer=TicketingSystem
      - JwtSettings__Audience=TicketingSystem.Users
      - RedisSettings__ConnectionString=redis:6379
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - redis
    networks:
      - ticketing-network

  # Ticketing Service (includes Events functionality)
  ticketing-service:
    build:
      context: .
      dockerfile: src/TicketingSystem.Ticketing/Dockerfile
    container_name: ticketing-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ticketingdb;Username=ticketinguser;Password=ticketingpass123;
      - JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLong12345
      - JwtSettings__Issuer=TicketingSystem
      - JwtSettings__Audience=TicketingSystem.Users
      - RedisSettings__ConnectionString=redis:6379
      - RabbitMQSettings__HostName=rabbitmq
      - RabbitMQSettings__Username=ticketinguser
      - RabbitMQSettings__Password=ticketingpass123
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - ticketing-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  ticketing-network:
    driver: bridge
